name: Python CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Install depenedncies
        run: |
          python -m pip install --upgrade pip
          pip install wheel networkx=2.5 pandas jinja2 requests
      - name: Run unittests
        run: python -m unittest
      - name: Run doctests
        run: |
          python -m doctest -v merge_baseline_configuration_xmls.py
          python -m doctest -v merge_condensed_sdrfs.py
          python -m doctest -v retrieve_data.py

